language: node_js
node_js:
    - "5.1.1"
services:
    - mongodb
before_script:
    - sleep 15
    - mongo --version
    - cp config/config.development.js.tpl config/config.development.js
    - DEBUG=server,monk:queries ./node_modules/.bin/babel-node src/index.js &
    - sleep 5
script:
  - gulp angry-lint
  - example/example.js
notifications:
  slack:
    secure: PSj5eta2pbs4STQLRDDVat/rs///2BUDR17sfFJyiy729FMFlPuK46hTv4DfFEY9NoiLFgt7wutGSZlI32VslOkotefhKfPifQUZXw4DiSTIhNteLOPwjloug3TnwrUeWcGOvHXwZVO7lZRri789qcAKTqFdtn74vvuh8PY769g=
branches:
  only:
    - master
    - integration
